spring:
  application:
    name: remessa

  datasource:
    url: jdbc:mysql://localhost:3306/remessa
    username: remessa
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

bcb:
  ptax:
    base-url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata

exchange-rate:
  scheduler:
    cron: "0 5 18 * * MON-FRI"