spring:
  application:
    name: remessa

  datasource:
    url: jdbc:mysql://localhost:3306/remessa
    username: remessa
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true